config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'teams#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'myteam' => 'sessions#index'
  get 'payment' => 'sessions#payment'
  post 'payment' => 'sessions#payment'

  resources :teams
  get 'page/index'
  root 'page#index'
  get 'admin/dashboard' => 'admin#dashboard'
  post 'admin/dashboard' => 'admin#dashboard'
  post 'admin/dashboard' => 'admin#update'

  get 'admin' => 'admin#login'
  post 'admin/login' => 'admin#check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
  has_attached_file :payment_proof, styles: { large:"800x800>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :payment_proof, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_secure_password validations: false

  validates :email, format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
              message: "Adresse email invalide."
            }

  validates :leader, presence: { message: "Le chef d'équipe doit être renseigné." }
  validates :email, presence: { message: "L'adresse email doit être renseigné." }

  validates :leader, uniqueness: { message: "Le chef d'équipe doit être unique." }
  validates :email, uniqueness: { message: "L'adresse email doit être unique." }

  validates :cin, presence: { message: "Le numéro cin doit être renseigné." }
  validates :phone, presence: { message: "Le numéro de téléphone doit être renseigné." }
  validates :password, presence: { message: "Le mot de passe doit être renseigné." }
  validates :contest, presence: { message: "La compétition doit être renseignée." }
  validates :robot, presence: { message: "Le nom du robot doit être renseigné." }
  validates :university, presence: { message: "L'établissement doit être renseigné." }

  validates :phone, length: { is: 8, message: "Numéro de téléphone non valide." }
  validates :cin, length: { in: 7..8, message: "Numéro CIN non valide." }

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
     @teams = Team.where(contest: params[:contests])
  end
  def login
  end

  def check
    if params[:name] == 'tunisino' && params[:password] == '123'
      flash[:info] = "Bienvenue Admin !"
      session[:name] = "tunisino"
      session[:password] = "123"
      redirect_to "/admin/dashboard"
    else
      flash[:info] = "Échec de la connexion"
      session[:name] = nil
      session[:password] = nil
      redirect_to "/admin/"
    end
  end
  def update
    @actualteam = Team.where(id: params[:activatedteam].to_i)

    Team.where(id: params[:activatedteam].to_i ).update_all( active: 1 )
    redirect_to "/teams/#{params[:activatedteam].to_i}"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def team_page
    team_page = params[:p]
  end
  def current_contest
    current_contest = params[:id]
  end
  def current_team
    Team.where(id: session[:team_id]).first
  end
  helper_method :current_team
  helper_method :current_contest
  helper_method :team_page
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def payment
    @myteam = Team.find(current_team.id)
    if @myteam && params[:payment_proof]
      Team.where( id: current_team.id ).update_all( payment_proof: params[:payment_proof])
    end
  end
  def new
  end
  def create
    team = Team.find_by_email(params[:email])
    if team && team.authenticate(params[:password])
      session[:team_id] = team.id
      redirect_to '/myteam', notice: 'Logged in!'
    else
      render :new
    end
  end
  def destroy
    session[:team_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
  def index
    @myteam = Team.find(current_team.id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    if current_team
      if ! (current_team.email == @team.email)
        redirect_to '/'
      end
    end
  end

  # GET /teams/new
  def new
    @team = Team.new

    @max = [0, 0, 0]

    @max[0] = Team.where(contest: 1).count
    @max[1] = Team.where(contest: 2).count
    @max[2] = Team.where(contest: 3).count
  end

  # GET /teams/1/edit
  def edit
    if current_team
      if ! (current_team.email == @team.email)
        redirect_to '/'
      end
    end
  end

  # POST /teams
  # POST /teams.json
  def create
    @max = [0, 0, 0]

    @max[0] = Team.where(contest: 1).count
    @max[1] = Team.where(contest: 2).count
    @max[2] = Team.where(contest: 3).count

    limit = [24, 1, 60]

    modified_params = team_params;
    modified_params[:active] = 0
    modified_params[:status] = 1
    modified_params[:date] = DateTime.now

    members = Team.where(contest: modified_params[:contest]).count

    if members
      if members < limit[modified_params[:contest].to_i - 1]
        @team = Team.new(modified_params)
        respond_to do |format|
          if @team.save
            session[:team_id] = @team.id
            format.html { redirect_to root_url, notice: 'Votre inscription est validée!' }
            format.json { render :show, status: :created, location: @team }
          else
            format.html { render :new }
            format.json { render json: @team.errors, status: :unprocessable_entity }
          end
        end
      elsif members < limit[modified_params[:contest].to_i - 1]*2 && members >= limit[modified_params[:contest].to_i - 1]
        modified_params[:status] = 0

        @team = Team.new(modified_params)
        rank = members - limit[modified_params[:contest].to_i - 1] + 1
        respond_to do |format|
          if @team.save
            session[:team_id] = @team.id
            format.html { redirect_to root_url, notice: "Vous êtes sur liste complémentaire au rang #{rank}" }
            format.json { render :show, status: :created, location: @team }
          else
            format.html { render :new }
            format.json { render json: @team.errors, status: :unprocessable_entity }
          end
        end

      else
        flash[:notice] = "Nous avons atteint le nombre maximum d'équipes autorisées!"
        redirect_to root_url
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_team
    @team = Team.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def team_params
    params.require(:team).permit(:leader, :email, :password, :password_confirmation, :phone, :cin, :contest, :date, :robot, :university, :payment_proof, :member1, :member2, :member3, :member4, :member5, :member6, :member7, :status, :active)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/dashboard.html.erb
<p id="notice"><%= notice %></p>
<% if session[:name] == "tunisino" && session[:password] == "123" %>
<div class="container">
  <div class = "page-header" style="text-align: center; margin: 40px 0;">
    <h1>
      Teams
    </h1>
  </div>

  <div class="form-inline">
    <p class="mr-sm-2" for="inlineFormCustomSelect">Choose Contest please: </label>
      <span><%= button_to 'Colisée de carthage', {:controller => "admin", :action => "dashboard", :contests => 1} , :method=>:post  %></span>
      <span><%= button_to 'La conquete de la méditerranée', {:controller => "admin", :action => "dashboard", :contests => 2} , :method=>:post  %></span>
      <span><%= button_to 'Collecte des ressources', {:controller => "admin", :action => "dashboard", :contests => 3} , :method=>:post  %></span>
  </div>

  <table class="table display responsive no-wrap" id="myTable">
    <thead class="thead-inverse">
      <tr>
        <th>Leader</th>
        <th>Email</th>
        <th>Cin</th>
        <th>Phone</th>
        <th>Date</th>
        <th>Contest</th>
        <th>Robot</th>
        <th>Other Members</th>
        <th>University</th>
        <th>Paymet proof</th>
        <th>Active</th>
        <th>Status</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @teams.each do |team| %>
      <tr>
        <td><%= team.leader %></td>
        <td><%= team.email %></td>
        <td><%= team.cin %></td>
        <td><%= team.phone %></td>
        <td><%= team.date %></td>
        <td><%= team.contest %></td>
        <td><%= team.robot %></td>
        <td><%= team.member1 %> ,<%= team.member2 %> ,<%= team.member3 %> ,<%= team.member4 %> ,<%= team.member5 %> ,<%= team.member6 %> ,<%= team.member7 %> </td>
        <td><%= team.university %></td>
        <td><a href="<%= team.payment_proof.url(:large) %>" target="_blank"><%= image_tag team.payment_proof.url(:thumb) %></a></td>
        <td><%= team.active %></td>
        <td><%= team.status %></td>

        <td>
          <td><%= button_to 'Activate', {:controller => "admin", :action => "update", :activatedteam => team.id} , :method=>:post  %></td>
        </td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Team', new_team_path %>

  <% end %>

</div>

app/views/admin/login.html.erb
<div class="container" style="margin-top: 100px;">
  <div class="row">
    <div class="col-6">
      <h1>Identifiez-vous</h1>
      <%= form_tag "/admin/login", method: :post do %>
      <div class="form-group row">
        <%= label_tag "Adresse Email:", nil, class: "col-3 col-form-label" %>
        <div class="col-9"><%= text_field_tag :name %></div>
      </div>
      <div class="form-group row">
        <%= label_tag "Mot de passe:", nil, class: "col-3 col-form-label" %>
        <div class="col-9"><%= password_field_tag :password %></div>
      </div>
      <div class="actions">
        <%= submit_tag "Log In", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
    <div class="col-6">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robots</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-faded" style="background-color: rgba(0, 0, 0, 1);">
    <a class="navbar-brand" href="/"><%= image_tag "logo.png", alt: "Logo", class: "img-responsive" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarNavDropdown" class="navbar-collapse collapse">
      <ul class="navbar-nav mr-auto">

      </ul>
      <ul class="navbar-nav">

        <% if current_team %>
        <li class="nav-item">
          <a href="/myteam" class="nav-link">Mon équipe</a>
        </li>
        <li class="nav-item">
          <span class="nav-link" style="color: #fff; !important">Logged in as <%= current_team.email %>.</span>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, class: "nav-link"%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Déjà inscrit ? Identifiez-vous", login_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, class: "alert alert-info") do %>
  <p><%= value %></p>
  <% end %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/page/index.html.erb
<div class="container gallery-container">
  <div class = "page-header" style="text-align: center; margin: 40px 0;">
     <h1>
       Inscription aux compétitions
     </h1>
  </div>

  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <div class="hovereffect">
        <%= image_tag "Colisee.jpg", alt: "Colisée", class: "img-responsive" %>
        <div class="overlay">
          <h2>Colisée de Carthage</h2>
          <a class="info" href="/signup/?id=1">Inscrivez-vous</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <div class="hovereffect">
        <%= image_tag "Conquete.jpg", alt: "Conquete", class: "img-responsive" %>
        <div class="overlay">
          <h2>La conquête de la Méditerranée</h2>
          <a class="info" href="/signup/?id=2">Inscrivez-vous</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <div class="hovereffect">
        <%= image_tag "Collecte.jpg", alt: "Collecte", class: "img-responsive" %>
        <div class="overlay">
          <h2>Collecte des Ressources</h2>
          <a class="info" href="/signup/?id=3">Inscrivez-vous</a>
        </div>
      </div>
    </div>
  </div>
</div>